# -*- coding: utf-8 -*-
"""word2vec_explorer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEtRrNAoy3d3h4ZG3FDA-cZkxFoVdl8a
"""

import gensim.downloader
w2v = gensim.downloader.load('word2vec-google-news-300')

def analogy(a, b, c):
  print(a+" : "+b+" :: "+c+" : ?")
  print([(w, round(c,3)) for w,c in w2v.most_similar(positive = [c,b], negative = [a])])

analogy("boy", "nephew", "girl")